kind: Service
apiVersion: v1
metadata:
  name: maniac-ml
  namespace: maniac-ml
  labels:
    k8s-app: maniac-ml
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    k8s-app: maniac-ml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: maniac-ml
  namespace: maniac-ml
  labels:
    k8s-app: maniac-ml
  annotations:
    kubernetes.io/ingress.class: slate
spec:
  tls:
  - hosts:
    - ml.maniac.uchicago.edu
    secretName: maniac-ml-tls
  rules:
  - host: ml.maniac.uchicago.edu
    http:
      paths:
      - path: /
        backend:
          serviceName: maniac-ml
          servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maniac-ml 
  namespace: maniac-ml
  labels:
    k8s-app: maniac-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: maniac-ml
  template:
    metadata:
      labels:
        k8s-app: maniac-ml
    spec:
      containers:
      - name: ml-front
        image: sslhep/ml_front:latest
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 80
          periodSeconds: 60
          initialDelaySeconds: 60
          timeoutSeconds: 10
        volumeMounts:
        - name: globus-conf-volume
          mountPath: "/etc/globus-conf/"
        - name: mg-conf-volume
          mountPath: "/etc/mg-conf/"
        - name: frontend-conf-volume
          mountPath: "/etc/ml-front-conf/"
      volumes:
      - name: globus-conf-volume
        secret:
          secretName: globus-secret
          items:
          - key: gconf
            path: globus-config.json
      - name: frontend-conf-volume
        secret:
          secretName: config
          items:
          - key: mlconf
            path: mlfront-config.json
      - name: mg-conf-volume
        secret:
          secretName: mg-config
          items:
          - key: mgconf
            path: config.json
      serviceAccountName: maniac-ml-fronter
