apiVersion: v1
kind: ServiceAccount
metadata:
  name: maniac-ml-fronter
  namespace: maniac-ml
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: maniac-ml-fronter-rbac
subjects:
  - kind: ServiceAccount
    name: maniac-ml-fronter
    namespace: maniac-ml
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io