apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-fronter
  namespace: ml
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ml-fronter-rbac
subjects:
  - kind: ServiceAccount
    name: ml-fronter
    namespace: ml
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io