kind: Service
apiVersion: v1
metadata:
  name: fiona1
  namespace: fiona1
  labels:
    k8s-app: fiona1
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    k8s-app: fiona1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiona1
  namespace: fiona1
  labels:
    k8s-app: fiona1
  annotations:
    kubernetes.io/ingress.class: slate
spec:
  tls:
  - hosts:
    - fiona1.uchicago.edu
    secretName: fiona1-tls
  rules:
  - host: fiona1.uchicago.edu
    http:
      paths:
      - path: /
            pathType: Prefix
            backend:
              service:
                name: fiona1
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiona1  
  namespace: fiona1
  labels:
    k8s-app: fiona1
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: fiona1
  template:
    metadata:
      labels:
        k8s-app: fiona1
    spec:
      containers:
      - name: ml-front
        image: sslhep/ml_front:latest
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 80
          periodSeconds: 60
          initialDelaySeconds: 60
          timeoutSeconds: 10
        volumeMounts:
          readOnly: true
        - name: globus-conf-volume
          mountPath: "/etc/globus-conf/"
        - name: mg-conf-volume
          mountPath: "/etc/mg-conf/"
        - name: frontend-conf-volume
          mountPath: "/etc/ml-front-conf/"
      volumes:
      - name: globus-conf-volume
        secret:
          secretName: globus-secret
          items:
          - key: gconf
            path: globus-config.json
      - name: frontend-conf-volume
        secret:
          secretName: config
          items:
          - key: mlconf
            path: mlfront-config.json
      - name: mg-conf-volume
        secret:
          secretName: mg-config
          items:
          - key: mgconf
            path: config.json
      serviceAccountName: fiona1-fronter
