apiVersion: v1
kind: ServiceAccount
metadata:
  name: fiona1-fronter
  namespace: fiona1
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fiona1-fronter-rbac
subjects:
  - kind: ServiceAccount
    name: fiona1-fronter
    namespace: fiona1
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io