apiVersion: v1
kind: ServiceAccount
apiVersion: v1
metadata:
  name: spark-acc
  namespace: fiona1
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: fiona1
  name: spark-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","services","configmaps"]
  verbs: ["get", "watch", "list", "create","delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-runner
  namespace: fiona1
subjects:
- kind: ServiceAccount
  name: spark-acc
  namespace: fiona1
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: spark-role
  apiGroup: rbac.authorization.k8s.io