kind: Service
apiVersion: v1
metadata:
  name: test-front
  namespace: test-ml
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ml.maniac.uchicago.edu
  labels:
    k8s-app: test-front
spec:
  type: LoadBalancer
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    k8s-app: test-front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-front  
  namespace: test-ml
  labels:
    k8s-app: test-front
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: test-front
  template:
    metadata:
      labels:
        k8s-app: test-front
    spec:
      containers:
      - name: ml-front
        image: sslhep/ml_front:latest
        command: ["node"]
        args: ["test-server.js"]
        ports:
          - containerPort: 443
          - containerPort: 80
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 443
          periodSeconds: 60
          initialDelaySeconds: 60
          timeoutSeconds: 10
        volumeMounts:
        - name: https-certs-volume
          mountPath: "/etc/https-certs/"
          readOnly: true
        - name: globus-conf-volume
          mountPath: "/etc/globus-conf/"
        - name: mg-conf-volume
          mountPath: "/etc/mg-conf/"
        - name: frontend-conf-volume
          mountPath: "/etc/ml-front-conf/"
      volumes:
      - name: https-certs-volume
        secret:
          secretName: cert-secret
          items:
          - key: key
            path: key.pem
            mode: 256 
          - key: cert
            path: cert.pem
      - name: globus-conf-volume
        secret:
          secretName: globus-secret
          items:
          - key: gconf
            path: globus-config.json
      - name: frontend-conf-volume
        secret:
          secretName: config
          items:
          - key: mlconf
            path: mlfront-config.json
      - name: mg-conf-volume
        secret:
          secretName: mg-config
          items:
          - key: mgconf
            path: config.json
      serviceAccountName: test-ml-fronter
