kind: Service
apiVersion: v1
metadata:
  name: privatejupyter  
  # namespace: ml
  annotations:
    external-dns.alpha.kubernetes.io/hostname: privatejupyter.slateci.net
  labels:
    k8s-app: privatejupyter
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9999
  selector:
    k8s-app: privatejupyter
---
kind: Pod
apiVersion: v1
metadata:
  name: privatejupyter
  # namespace: ml
  labels:
    k8s-app: privatejupyter
spec:
  containers:
  - name: privatejupyter
    image: ivukotic/ml_platform_auto:latest
    args: ["/.run", "/ML_platform_tests/Assemble_tutorial_jlab.sh"] 
    ports:
      - containerPort: 9999
    resources: 
      requests:
        cpu: 1
        memory: "12Gi"
        nvidia.com/gpu: 1
      limits: 
        cpu: 1
        memory: "16Gi"
        nvidia.com/gpu: 1 # requests and limits mus be the same ?!
    volumeMounts:
    - name: local-scratch
      mountPath: /data/
      readOnly: false
  volumes:
  - name: local-scratch
    hostPath:
      path: /data
  nodeSelector:
    mlnode: "true"
  restartPolicy: Always
