name: Build ML front image

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: ivukotic/atlas-xcache
          tags: latest
          directory: "atlas-xcache"
          dockerfile: "atlas-xcache/Dockerfile"
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
